design_point:
  pressure_ratio: 2.0
  mass_flow_rate: 12.7

efficiencies:
  compressor: 0.88
  turbine: 0.92

physics:
  # Helium
  gamma: 1.66
  cp_gas: 5195.0
  
  generator_efficiency: 0.98
  expansion_recovery_factor: 0.90