# SIMULATION SETTINGS
time_settings:
  start_time: 0.0
  duration: 86400.0   # 24 Hours (in seconds)
  dt: 1.0             # Calculate every 1 second

logging:
  save_to_csv: true
  output_dir: "results"